version: '3.8'
services:
  db:
    image: postgres:15
    container_name: malware_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: malware_analysis_db
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: malware_redis
    ports:
      - "6379:6379"
    restart: always
